#!/bin/sh

git clone --bare https://github.com/bgreenb11/dotfiles ~/dotfiles

function config {
    /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

mkdir -p ~/.dotfiles_bk

config checkout

if [ $? = 0 ]; then
    echo "Checked out config.";
else
    echo "Backing up pre-existing dotfiles...";
    config checkout 2>&1 | egrep "\s+\." | awk { 'print $1'} | xargs  -I{} mv ~/.dotfiles_bk/{}
fi;

config checkout
config config status.showUntrackedFiles no

echo "Downloading submodules..."
config submodules update --init --recursive -j 4 --quiet

# This cronjob will set the QUERY_UPDATE to ask for an update upon login after the first of every month
crontab -l 2> /dev/null | { cat; echo '* * 1 * * $QUERY_UPDATE=1' } | crontab -

export QUERY_UPDATE=0
